<div class="item-showcase">
<?php foreach ($attachments as $attachment): ?>
    <?php
    $item = $attachment->item();
    if (!$item) continue;
    $caption = $attachment->caption();
    $media = $attachment->media() ?: $item->primaryMedia();
    ?>
    <div class="item resource">
        <?php if ($media): ?>
            <?php echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType), null, ['class' => 'item-showcase__media']); ?>
        <?php endif; ?>
        <div class="item-showcase__content">
            <?php echo $this->ResourceTags($item); ?>
            <div class="item-showcase__text">
                <?php if ($this->showTitleOption === 'item_title'): ?>
                    <h3><?php echo $item->link($item->displayTitle()); ?></h3>
                <?php elseif ($this->showTitleOption === 'file_name' && $media): ?>
                    <h3><?php echo $this->escapeHtml($media->displayTitle()); ?></h3>
                <?php endif; ?>
                <?php if ($caption): ?>
                    <div class="caption"><?php echo $caption; ?></div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
</div>
