<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$thumbnail = $this->plugin('thumbnail');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
$query = $this->params()->fromQuery();


$this->headLink()->appendStylesheet($this->assetUrl('css/hierarchy.css', 'Hierarchy'));
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource browse hierarchy-module');
?>
<?php
if ($hierarchyGrouping->getLabel()) {
    echo $this->pageTitle($hierarchyGrouping->getLabel(), 1);
} else if ($hierarchyGrouping->getItemSet()) {
    echo $this->pageTitle($hierarchyGrouping->getItemSet()->displayTitle(null, $valueLang), 1);
}
?>

<div class="hierarchy-row">
    <?php $tree = $this->HierarchyTree($hierarchyGrouping, $valueLang); ?>
    <div class="hierarchy-sidebar-content"><div class="hierarchy-metadata"><div class="hierarchy-filters">
        <?php if ($this->siteSetting('hierarchy_show_label') && $hierarchyGrouping->getHierarchy()->getLabel()): ?>
            <h2><?php echo $escape($hierarchyGrouping->getHierarchy()->getLabel()); ?></h2>
        <?php endif; ?>
        <?php echo $this->partial('common/hierarchy-tree', ['nodes' => $tree['nodes']]); ?>
    </div>
    <?php if ($this->siteSetting('hierarchy_display_itemSets') && $tree['itemSets']): ?>
        <div class="hierarchy-item-sets">
            <?php echo $escape($translate('Contains resources from:')); ?>
            <?php foreach ($tree['itemSets'] as $index => $set): ?>
                <?php echo $index ? ', ' : ''; ?><?php echo $set->link($set->displayTitle()); ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    </div></div>

    <div class="hierarchy-main-content">
        <?php
        // If hierarchy_show_itemset_metadata checked, display item set metadata
        if ($this->siteSetting('hierarchy_show_itemSet_metadata') && $itemSet):
            $headingTerm = $this->siteSetting('browse_heading_property_term');
            $bodyTerm = $this->siteSetting('browse_body_property_term');
            $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $itemSet->displayTitle(null, $valueLang);
            $body = $bodyTerm ? $itemSet->value($bodyTerm, ['lang' => $valueLang]) : $itemSet->displayDescription(null, $valueLang);
        ?>
        <ul class="resource-list">
        <li class="item-set resource">
            <div class="hierarchy-itemset-metadata">
                <?php
                $linkContent = sprintf('%s<span class="resource-name">%s</span>',
                    $thumbnail($itemSet, 'medium'),
                    $escape($heading));
                echo $itemSet->linkRaw($linkContent, null, ['class' => 'resource-link']);
                ?>
                <?php if ($body): ?>
                <div class="description"><?php echo $escape($body); ?></div>
                <?php endif; ?>
            </div>
        </li>
        </ul>
        <?php endif; ?>

        <div class="hierarchy-items">
            <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>

            <?php echo $this->searchFilters(); ?>

            <div class="browse-controls">
                <?php echo $this->pagination(); ?>
                <?php echo $this->hyperlink($translate('Search the collection'), $this->DreSearchUrl(), ['class' => 'collection-search']); ?>
                <?php echo $this->browse()->renderSortSelector('items'); ?>
            </div>

            <?php $this->trigger('view.browse.before'); ?>
            <ul class="resource-list">
                <?php
                $headingTerm = $this->siteSetting('browse_heading_property_term');
                $bodyTerm = $this->siteSetting('browse_body_property_term');
                $bodyTruncate = $this->themeSetting('truncate_body_property');
                foreach ($items as $item):
                    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $item->displayTitle(null, $valueLang);
                    $body = $bodyTerm ? $item->value($bodyTerm, ['lang' => $valueLang]) : $item->displayDescription(null, $valueLang);
                    $primaryMedia = $item->primaryMedia();
                    $thumbnail = '';
                    if ($primaryMedia) {
                        $altText = $primaryMedia->altText() ?: $primaryMedia->displayTitle() ?: '';
                        $thumbnail = $this->thumbnail($primaryMedia, 'square', ['alt' => $altText]);
                    }
                    echo $this->partial('common/resource-card', [
                        'resource' => $item,
                        'heading' => $heading,
                        'body' => $body,
                        'bodyTruncate' => $bodyTruncate,
                        'thumbnail' => $thumbnail,
                        'tag' => 'li',
                        'isGrid' => false,
                    ]);
                endforeach; ?>
            </ul>
            <div class="browse-controls">
                <?php echo $this->pagination(); ?>
            </div>
            <?php $this->trigger('view.browse.after'); ?>
        </div>
    </div>
</div>
